export const MATCH_ACTIONS = Object.freeze({
  HYDRATE: "match/hydrate",
  HYDRATE_FAILED: "match/hydrateFailed",
  SELECT_PLAYER: "match/selectPlayer",
  CHANGE_BOWLER: "match/changeBowler",
  SWITCH_STRIKE: "match/switchStrike",
  RETIRE_BATTER: "match/retireBatter",
  SCORE_RUN: "match/scoreRun",
  TAKE_WICKET: "match/takeWicket",
  UNDO: "match/undo",
  START_NEXT_INNINGS: "match/startNextInnings",
  START_SUPER_OVER: "match/startSuperOver",
  DECLARE_TEST_INNINGS: "match/declareTestInnings",
  FINISH_TEST_DRAW: "match/finishTestDraw",
  SET_EXTRA_MODE: "ui/setExtraMode",
  TOGGLE_EXTRA_MODE: "ui/toggleExtraMode",
  REPLACE_MATCH: "match/replace",
  REPLACE_PERSISTED_MATCH: "match/replacePersisted",
  UPDATE_SETTINGS: "match/updateSettings",
  ADD_TEAM_PLAYER: "match/addTeamPlayer",
  REMOVE_TEAM_PLAYER: "match/removeTeamPlayer",
  PERSISTING: "persistence/saving",
  PERSISTED: "persistence/saved",
  PERSIST_FAILED: "persistence/failed",
});
