export const queryKeys = Object.freeze({
  seasons: ["seasons"],
  seasonMatches: (seasonId) => ["seasonMatches", seasonId],
  match: (matchId) => ["match", matchId],
  leaderboardRoot: ["leaderboard"],
  leaderboard: (type, filters) => ["leaderboard", type, filters],
  partnerships: (view, filters) => ["partnerships", view, filters],
  rivalries: (filters) => ["rivalries", filters],
  playerComparison: (filters) => ["playerComparison", filters],
  playerProfileRoot: ["playerProfile"],
  playerProfile: (playerId, seasonId, matchType) => [
    "playerProfile",
    playerId,
    seasonId || "all",
    matchType || "all",
  ],
  teamProfileRoot: ["teamProfile"],
  teamProfile: (teamId, seasonId, matchType) => [
    "teamProfile",
    teamId,
    seasonId || "all",
    matchType || "all",
  ],
  teamsRoot: ["teams"],
  teams: (seasonId) => ["teams", seasonId || "ALL"],
  globalSearch: (query) => ["globalSearch", query],
  teamSearch: (query) => ["teamSearch", query],
  playerSearch: (query) => ["playerSearch", query],
  teamSeasonPlayers: (teamId, seasonId) => [
    "teamSeasonPlayers",
    teamId,
    seasonId,
  ],
});
